[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "frame-ancestors frame.bloglovin.com"
    X-Frame-Options = "DENY" # Fallback value for browsers that don't support CSP2+, will also disallow frame.bloglovin.com unfortunately 
    X-XSS-Protection = "1; mode=block"
